version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- ps: dotnet restore
after_build:
- ps: dotnet pack -c release
install:
- nuget sources add -Name MyAccountFeed42 -Source https://ci.appveyor.com/nuget/dshe -UserName %nuget_user% -Password %nuget_password%
build:
  verbosity: minimal
test_script:
- ps: dotnet test .\Stringification.Tests\Stringification.Tests.csproj
artifacts:
- path: '**\*.nupkg'
nuget:
  account_feed: true
